version: '3.4'

services:

  mifrontend:
    image: mifrontend
    ports:
    - 8080:8080
    build:
        context: ../TODO-APP/todoapp-frontend/.
        dockerfile: Dockerfile
    container_name: mifrontend
    depends_on:
    - sqldata
    - miproyecto
