version: '3.4'

services:

  ms-sql-server:
    image: mcr.microsoft.com/mssql/server:2019-latest
    ports:
      - 1450:1433
    environment:
      - SA_PASSWORD=Mypassword*7
      - ACCEPT_EULA=Y
    container_name: ms-sql-server

  miproyecto:
    image: ${DOCKER_REGISTRY-}miproyecto
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"
    build:
      context: .
      dockerfile: MiProyecto/Dockerfile
    depends_on:
        - ms-sql-server
    container_name: miproyecto
